name: publish latest

on:
  release:
    types: [released]
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: install dependencies
        run: npm ci
      - name: build library
        run: npm run build
      - name: publish library
        working-directory: dist/angular
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
