name: publish latest

on:
  release:
    types: [released]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - name: publish library
        working-directory: dist
        run: npm publish --access=public --tag lts-6
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
